"""initial tables

Revision ID: edc8df0417b4
Revises: 
Create Date: 2026-03-27 19:26:55.165667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edc8df0417b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intake_id', sa.UUID(), nullable=False),
    sa.Column('selected_program', sa.String(length=255), nullable=True),
    sa.Column('pipeline_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_intake_id'), 'candidates', ['intake_id'], unique=True)
    op.create_index(op.f('ix_candidates_pipeline_status'), 'candidates', ['pipeline_status'], unique=False)
    op.create_index(op.f('ix_candidates_selected_program'), 'candidates', ['selected_program'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_competencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_name'), 'programs', ['name'], unique=True)
    op.create_table('candidate_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('positive_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('caution_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_quality_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewer_guidance', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_explanations_candidate_id'), 'candidate_explanations', ['candidate_id'], unique=True)
    op.create_table('candidate_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('age_eligible', sa.Boolean(), nullable=True),
    sa.Column('language_threshold_met', sa.Boolean(), nullable=True),
    sa.Column('language_exam_type', sa.String(length=50), nullable=True),
    sa.Column('has_video', sa.Boolean(), nullable=False),
    sa.Column('data_completeness', sa.Float(), nullable=True),
    sa.Column('data_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_metadata_candidate_id'), 'candidate_metadata', ['candidate_id'], unique=True)
    op.create_table('candidate_model_inputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('video_transcript', sa.Text(), nullable=True),
    sa.Column('essay_text', sa.Text(), nullable=True),
    sa.Column('internal_test_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('project_descriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience_summary', sa.Text(), nullable=True),
    sa.Column('asr_confidence', sa.Float(), nullable=True),
    sa.Column('asr_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_model_inputs_candidate_id'), 'candidate_model_inputs', ['candidate_id'], unique=True)
    op.create_table('candidate_pii',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_pii_candidate_id'), 'candidate_pii', ['candidate_id'], unique=True)
    op.create_table('candidate_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('sub_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_priority_index', sa.Float(), nullable=True),
    sa.Column('recommendation_status', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('shortlist_eligible', sa.Boolean(), nullable=True),
    sa.Column('ranking_position', sa.Integer(), nullable=True),
    sa.Column('scoring_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_scores_candidate_id'), 'candidate_scores', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_candidate_scores_recommendation_status'), 'candidate_scores', ['recommendation_status'], unique=False)
    op.create_index(op.f('ix_candidate_scores_review_priority_index'), 'candidate_scores', ['review_priority_index'], unique=False)
    op.create_index(op.f('ix_candidate_scores_shortlist_eligible'), 'candidate_scores', ['shortlist_eligible'], unique=False)
    op.create_table('nlp_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=255), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nlp_signals_candidate_id'), 'nlp_signals', ['candidate_id'], unique=True)
    op.create_table('reviewer_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewer_actions_candidate_id'), 'reviewer_actions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_reviewer_actions_reviewer_id'), 'reviewer_actions', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewer_actions_reviewer_id'), table_name='reviewer_actions')
    op.drop_index(op.f('ix_reviewer_actions_candidate_id'), table_name='reviewer_actions')
    op.drop_table('reviewer_actions')
    op.drop_index(op.f('ix_nlp_signals_candidate_id'), table_name='nlp_signals')
    op.drop_table('nlp_signals')
    op.drop_index(op.f('ix_candidate_scores_shortlist_eligible'), table_name='candidate_scores')
    op.drop_index(op.f('ix_candidate_scores_review_priority_index'), table_name='candidate_scores')
    op.drop_index(op.f('ix_candidate_scores_recommendation_status'), table_name='candidate_scores')
    op.drop_index(op.f('ix_candidate_scores_candidate_id'), table_name='candidate_scores')
    op.drop_table('candidate_scores')
    op.drop_index(op.f('ix_candidate_pii_candidate_id'), table_name='candidate_pii')
    op.drop_table('candidate_pii')
    op.drop_index(op.f('ix_candidate_model_inputs_candidate_id'), table_name='candidate_model_inputs')
    op.drop_table('candidate_model_inputs')
    op.drop_index(op.f('ix_candidate_metadata_candidate_id'), table_name='candidate_metadata')
    op.drop_table('candidate_metadata')
    op.drop_index(op.f('ix_candidate_explanations_candidate_id'), table_name='candidate_explanations')
    op.drop_table('candidate_explanations')
    op.drop_index(op.f('ix_programs_name'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_candidates_selected_program'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_pipeline_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_intake_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
